version: '3.1'

services:
  permission:
    build: .
    networks:
      - my-network
    ports:
      - 5000:5000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.5
    networks:
      - my-network
    ports:
      - 27017:27017

networks:
  my-network:
    driver: bridge