version: '3.1'

services:
  permission:
    build: .
    restart: always
    container_name: permission
    ports:
      - 8080:5000
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.5
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
